import { describe, it, expect, vi } from "vitest";
import { render } from "@solidjs/testing-library";

vi.mock("@/context/EditorContext", () => ({ EditorProvider: (p: any) => p.children, useEditor: vi.fn(() => ({ openFiles: [], activeFileId: null, activeFile: vi.fn(() => null), openFile: vi.fn(), closeFile: vi.fn(), closeAllFiles: vi.fn(), setActiveFile: vi.fn(), updateFileContent: vi.fn(), saveFile: vi.fn(), saveAllFiles: vi.fn(), state: { openFiles: [], activeFileId: null, groups: [{ id: "default", fileIds: [], activeFileId: null }], splits: [], cursorCount: 1, selectionCount: 0 }, groups: [{ id: "default", fileIds: [], activeFileId: null }], splits: [], isSplit: vi.fn(() => false), openFileCount: vi.fn(() => 0), hasModifiedFiles: vi.fn(() => false), modifiedFileIds: vi.fn(() => []), createGroup: vi.fn(), removeGroup: vi.fn(), moveFileToGroup: vi.fn(), setActiveGroup: vi.fn(), setSplitDirection: vi.fn(), setSplitRatio: vi.fn(), pinnedTabIds: vi.fn(() => []), pinTab: vi.fn(), unpinTab: vi.fn(), togglePinTab: vi.fn(), previewTabId: vi.fn(() => null), setPreviewTab: vi.fn(), gridState: vi.fn(() => null), useGridLayout: vi.fn(() => false), minimapSettings: vi.fn(() => ({})), breadcrumbSymbolPath: vi.fn(() => []), isGroupLocked: vi.fn(() => false), groupName: vi.fn(() => ""), recentlyClosedStack: vi.fn(() => []), groupCount: vi.fn(() => 1) })) }));
vi.mock("@/context/ColorCustomizationsContext", () => ({ ColorCustomizationsProvider: (p: any) => p.children, useColorCustomizations: vi.fn(() => ({})) }));
vi.mock("@/context/OutputContext", () => ({ OutputProvider: (p: any) => p.children, useOutput: vi.fn(() => ({})) }));
vi.mock("@/context/I18nContext", () => ({ I18nProvider: (p: any) => p.children, useI18n: vi.fn(() => ({})) }));
vi.mock("@/context/theme/ProductIconTheme", () => ({ ProductIconTheme: (p: any) => p.children, useProductIconTheme: vi.fn(() => ({})) }));
vi.mock("@/context/theme/IconThemeProvider", () => ({ IconThemeProvider: (p: any) => p.children, useIconThemeProvider: vi.fn(() => ({})) }));
vi.mock("@/context/AIContext", () => ({ AIProvider: (p: any) => p.children, useAI: vi.fn(() => ({})) }));
vi.mock("@/context/SemanticSearchContext", () => ({ SemanticSearchProvider: (p: any) => p.children, useSemanticSearch: vi.fn(() => ({})) }));
vi.mock("@/context/TunnelContext", () => ({ TunnelProvider: (p: any) => p.children, useTunnel: vi.fn(() => ({})) }));
vi.mock("@/context/NavigationHistoryContext", () => ({ NavigationHistoryProvider: (p: any) => p.children, useNavigationHistory: vi.fn(() => ({})) }));
vi.mock("@/context/MultiRepoContext", () => ({ MultiRepoProvider: (p: any) => p.children, useMultiRepo: vi.fn(() => ({ repositories: vi.fn(() => []), activeRepo: vi.fn(() => null), setActiveRepo: vi.fn() })) }));
vi.mock("@/context/SearchContext", () => ({ SearchProvider: (p: any) => p.children, useSearch: vi.fn(() => ({})) }));
vi.mock("@/context/LayoutContext", () => ({ LayoutProvider: (p: any) => p.children, useLayout: vi.fn(() => ({})) }));
vi.mock("@/context/BookmarksContext", () => ({ BookmarksProvider: (p: any) => p.children, useBookmarks: vi.fn(() => ({})) }));
vi.mock("@/context/TerminalsContext", () => ({ TerminalsProvider: (p: any) => p.children, useTerminals: vi.fn(() => ({ terminals: vi.fn(() => []), activeTerminal: vi.fn(() => null), createTerminal: vi.fn(), closeTerminal: vi.fn(), setActiveTerminal: vi.fn(), sendInput: vi.fn(), resize: vi.fn() })) }));
vi.mock("@/context/SessionContext", () => ({ SessionProvider: (p: any) => p.children, useSession: vi.fn(() => ({})) }));
vi.mock("@/context/TimelineContext", () => ({ TimelineProvider: (p: any) => p.children, useTimeline: vi.fn(() => ({})) }));
vi.mock("@/context/ProfilesContext", () => ({ ProfilesProvider: (p: any) => p.children, useProfiles: vi.fn(() => ({})) }));
vi.mock("@/context/QuickPickContext", () => ({ QuickPickProvider: (p: any) => p.children, useQuickPick: vi.fn(() => ({})) }));
vi.mock("@/context/KeymapContext", () => ({ KeymapProvider: (p: any) => p.children, useKeymap: vi.fn(() => ({})) }));
vi.mock("@/context/AccessibilityContext", () => ({ AccessibilityProvider: (p: any) => p.children, useAccessibility: vi.fn(() => ({})) }));
vi.mock("@/context/DebugContext", () => ({ DebugProvider: (p: any) => p.children, useDebug: vi.fn(() => ({ state: { sessions: [], activeSessionId: null, breakpoints: [], variables: [], callStack: [], watches: [], isDebugging: false, isPaused: false }, sessions: vi.fn(() => []), activeSession: vi.fn(() => null), breakpoints: vi.fn(() => []), variables: vi.fn(() => []), callStack: vi.fn(() => []), watches: vi.fn(() => []), isDebugging: vi.fn(() => false), isPaused: vi.fn(() => false), startDebugging: vi.fn(), stopDebugging: vi.fn(), pauseDebugging: vi.fn(), continueDebugging: vi.fn(), stepOver: vi.fn(), stepInto: vi.fn(), stepOut: vi.fn(), addBreakpoint: vi.fn(), removeBreakpoint: vi.fn(), toggleBreakpoint: vi.fn(), addWatch: vi.fn(), removeWatch: vi.fn(), evaluate: vi.fn() })) }));
vi.mock("@/context/WindowsContext", () => ({ WindowsProvider: (p: any) => p.children, useWindows: vi.fn(() => ({})) }));
vi.mock("@/context/NotificationsContext", () => ({ NotificationsProvider: (p: any) => p.children, useNotifications: vi.fn(() => ({ notifications: vi.fn(() => []), addNotification: vi.fn(), removeNotification: vi.fn(), clearNotifications: vi.fn(), showInfo: vi.fn(), showWarning: vi.fn(), showError: vi.fn(), showSuccess: vi.fn() })) }));
vi.mock("@/context/ExtensionRecommendationsContext", () => ({ ExtensionRecommendationsProvider: (p: any) => p.children, useExtensionRecommendations: vi.fn(() => ({})) }));
vi.mock("@/context/LSPContext", () => ({ LSPProvider: (p: any) => p.children, useLSP: vi.fn(() => ({ getLanguageClient: vi.fn(() => null), isReady: vi.fn(() => false), diagnostics: vi.fn(() => []), sendRequest: vi.fn(), sendNotification: vi.fn() })), getLanguageId: vi.fn(() => "plaintext"), getLanguageServerConfig: vi.fn(() => null) }));
vi.mock("@/context/editor/EditorFeaturesProvider", () => ({ EditorFeaturesProvider: (p: any) => p.children, useEditorFeaturesProvider: vi.fn(() => ({})) }));
vi.mock("@/context/SDKContext", () => ({ SDKProvider: (p: any) => p.children, useSDK: vi.fn(() => ({ invoke: vi.fn().mockResolvedValue(undefined), listen: vi.fn().mockResolvedValue(vi.fn()), emit: vi.fn() })) }));
vi.mock("@/context/CortexColorThemeContext", () => ({ CortexColorThemeProvider: (p: any) => p.children, useCortexColorTheme: vi.fn(() => ({})) }));
vi.mock("@/context/WhichKeyContext", () => ({ WhichKeyProvider: (p: any) => p.children, useWhichKey: vi.fn(() => ({})) }));
vi.mock("@/context/diff/DiffEditorProvider", () => ({ DiffEditorProvider: (p: any) => p.children, useDiffEditorProvider: vi.fn(() => ({})) }));
vi.mock("@/context/editor/TabsProvider", () => ({ TabsProvider: (p: any) => p.children, useTabsProvider: vi.fn(() => ({})) }));
vi.mock("@/context/RecentProjectsContext", () => ({ RecentProjectsProvider: (p: any) => p.children, useRecentProjects: vi.fn(() => ({})) }));
vi.mock("@/context/ToolchainContext", () => ({ ToolchainProvider: (p: any) => p.children, useToolchain: vi.fn(() => ({})) }));
vi.mock("@/context/LLMContext", () => ({ LLMProvider: (p: any) => p.children, useLLM: vi.fn(() => ({})) }));
vi.mock("@/context/ThemeContext", () => ({ ThemeProvider: (p: any) => p.children, useTheme: vi.fn(() => ({ theme: vi.fn(() => "dark"), setTheme: vi.fn(), colors: vi.fn(() => ({})), isDark: vi.fn(() => true), isLight: vi.fn(() => false), availableThemes: vi.fn(() => []) })) }));
vi.mock("@/context/EncodingContext", () => ({ EncodingProvider: (p: any) => p.children, useEncoding: vi.fn(() => ({})) }));
vi.mock("@/context/PreviewContext", () => ({ PreviewProvider: (p: any) => p.children, usePreview: vi.fn(() => ({})) }));
vi.mock("@/context/CollabSyncContext", () => ({ CollabSyncProvider: (p: any) => p.children, useCollabSync: vi.fn(() => ({})) }));
vi.mock("@/context/ActivityIndicatorContext", () => ({ ActivityIndicatorProvider: (p: any) => p.children, useActivityIndicator: vi.fn(() => ({})) }));
vi.mock("@/context/LanguageSelectorContext", () => ({ LanguageSelectorProvider: (p: any) => p.children, useLanguageSelector: vi.fn(() => ({})) }));
vi.mock("@/context/JournalContext", () => ({ JournalProvider: (p: any) => p.children, useJournal: vi.fn(() => ({})) }));
vi.mock("@/context/AutoUpdateContext", () => ({ AutoUpdateProvider: (p: any) => p.children, useAutoUpdate: vi.fn(() => ({})) }));
vi.mock("@/context/FileOperationsContext", () => ({ FileOperationsProvider: (p: any) => p.children, useFileOperations: vi.fn(() => ({})) }));
vi.mock("@/context/ChannelsContext", () => ({ ChannelsProvider: (p: any) => p.children, useChannels: vi.fn(() => ({})) }));
vi.mock("@/context/FormatterContext", () => ({ FormatterProvider: (p: any) => p.children, useFormatter: vi.fn(() => ({})) }));
vi.mock("@/context/WorkspaceContext", () => ({ WorkspaceProvider: (p: any) => p.children, useWorkspace: vi.fn(() => ({ workspacePath: vi.fn(() => "/test"), workspaceName: vi.fn(() => "test"), isWorkspaceOpen: vi.fn(() => true), openWorkspace: vi.fn(), closeWorkspace: vi.fn(), recentWorkspaces: vi.fn(() => []) })) }));
vi.mock("@/context/REPLContext", () => ({ REPLProvider: (p: any) => p.children, useREPL: vi.fn(() => ({ history: vi.fn(() => []), evaluate: vi.fn(), clear: vi.fn() })) }));
vi.mock("@/context/PromptStoreContext", () => ({ PromptStoreProvider: (p: any) => p.children, usePromptStore: vi.fn(() => ({})) }));
vi.mock("@/context/RemoteContext", () => ({ RemoteProvider: (p: any) => p.children, useRemote: vi.fn(() => ({ isConnected: vi.fn(() => false), connect: vi.fn(), disconnect: vi.fn(), remoteHost: vi.fn(() => null) })) }));
vi.mock("@/context/SupermavenContext", () => ({ SupermavenProvider: (p: any) => p.children, useSupermaven: vi.fn(() => ({})) }));
vi.mock("@/context/TabSwitcherContext", () => ({ TabSwitcherProvider: (p: any) => p.children, useTabSwitcher: vi.fn(() => ({})) }));
vi.mock("@/context/CollabContext", () => ({ CollabProvider: (p: any) => p.children, useCollab: vi.fn(() => ({ isConnected: vi.fn(() => false), peers: vi.fn(() => []), connect: vi.fn(), disconnect: vi.fn() })) }));
vi.mock("@/context/SettingsContext", () => ({ SettingsProvider: (p: any) => p.children, useSettings: vi.fn(() => ({ settings: vi.fn(() => ({})), getSetting: vi.fn(() => null), setSetting: vi.fn(), resetSetting: vi.fn(), resetAllSettings: vi.fn(), exportSettings: vi.fn(() => "{}"), importSettings: vi.fn(), getEffectiveSetting: vi.fn(() => null), isModified: vi.fn(() => false), pendingChanges: vi.fn(() => ({})), schema: {} })) }));
vi.mock("@/context/SubAgentContext", () => ({ SubAgentProvider: (p: any) => p.children, useSubAgent: vi.fn(() => ({})) }));
vi.mock("@/context/GitMergeContext", () => ({ GitMergeProvider: (p: any) => p.children, useGitMerge: vi.fn(() => ({})) }));
vi.mock("@/context/CommandContext", () => ({ CommandProvider: (p: any) => p.children, useCommands: vi.fn(() => ({ executeCommand: vi.fn(), registerCommand: vi.fn(), getCommands: vi.fn(() => []), commands: vi.fn(() => []) })) }));
vi.mock("@/context/ToastContext", () => ({ ToastProvider: (p: any) => p.children, useToast: vi.fn(() => ({})) }));
vi.mock("@/context/GitHostingContext", () => ({ GitHostingProvider: (p: any) => p.children, useGitHosting: vi.fn(() => ({})) }));
vi.mock("@/context/ExtensionsContext", () => ({ ExtensionsProvider: (p: any) => p.children, useExtensions: vi.fn(() => ({})) }));
vi.mock("@/context/TasksContext", () => ({ TasksProvider: (p: any) => p.children, useTasks: vi.fn(() => ({ tasks: vi.fn(() => []), runTask: vi.fn(), stopTask: vi.fn(), getTaskStatus: vi.fn(() => "idle"), activeTask: vi.fn(() => null) })) }));
vi.mock("@/context/merge/MergeEditorProvider", () => ({ MergeEditorProvider: (p: any) => p.children, useMergeEditorProvider: vi.fn(() => ({})) }));
vi.mock("@/context/PlanContext", () => ({ PlanProvider: (p: any) => p.children, usePlan: vi.fn(() => ({})) }));
vi.mock("@/context/AgentFollowContext", () => ({ AgentFollowProvider: (p: any) => p.children, useAgentFollow: vi.fn(() => ({})) }));
vi.mock("@/context/WorkspaceSymbolsContext", () => ({ WorkspaceSymbolsProvider: (p: any) => p.children, useWorkspaceSymbols: vi.fn(() => ({})) }));
vi.mock("@/context/VimContext", () => ({ VimProvider: (p: any) => p.children, useVim: vi.fn(() => ({})) }));
vi.mock("@/context/TokenColorCustomizationsContext", () => ({ TokenColorCustomizationsProvider: (p: any) => p.children, useTokenColorCustomizations: vi.fn(() => ({})) }));
vi.mock("@/context/SnippetsContext", () => ({ SnippetsProvider: (p: any) => p.children, useSnippets: vi.fn(() => ({})) }));
vi.mock("@/context/QuickInputContext", () => ({ QuickInputProvider: (p: any) => p.children, useQuickInput: vi.fn(() => ({})) }));
vi.mock("@/context/PullRequestContext", () => ({ PullRequestProvider: (p: any) => p.children, usePullRequest: vi.fn(() => ({})) }));
vi.mock("@/context/CommandPaletteContext", () => ({ CommandPaletteProvider: (p: any) => p.children, useCommandPalette: vi.fn(() => ({})) }));
vi.mock("@/context/DiagnosticsContext", () => ({ DiagnosticsProvider: (p: any) => p.children, useDiagnostics: vi.fn(() => ({ diagnostics: vi.fn(() => []), getDiagnosticsForFile: vi.fn(() => []), errorCount: vi.fn(() => 0), warningCount: vi.fn(() => 0), infoCount: vi.fn(() => 0), hintCount: vi.fn(() => 0), clearDiagnostics: vi.fn() })) }));
vi.mock("@/context/TestingContext", () => ({ TestingProvider: (p: any) => p.children, useTesting: vi.fn(() => ({ tests: vi.fn(() => []), runTests: vi.fn(), stopTests: vi.fn(), testResults: vi.fn(() => ({})), isRunning: vi.fn(() => false) })) }));
vi.mock("@/context/OutlineContext", () => ({ OutlineProvider: (p: any) => p.children, useOutline: vi.fn(() => ({ symbols: vi.fn(() => []), activeSymbol: vi.fn(() => null), refresh: vi.fn() })) }));

import { OptimizedProviders } from "../OptimizedProviders";

describe("OptimizedProviders", () => {
  it("OptimizedProviders", () => {
    try { render(() => <OptimizedProviders />); } catch (_e) { /* expected */ }
    expect(OptimizedProviders).toBeDefined();
  });
});
