#[macro_export]
macro_rules! ai_commands {
    (@commands $callback:ident [ $($acc:tt)* ]) => {
        $callback!([ $($acc)*
            // AI commands
            $crate::ai::ai_complete,
            $crate::ai::ai_stream,
            $crate::ai::ai_list_models,
            $crate::ai::ai_get_provider_models,
            $crate::ai::ai_configure_provider,
            $crate::ai::ai_remove_provider,
            $crate::ai::ai_init_threads,
            $crate::ai::ai_create_thread,
            $crate::ai::ai_get_thread,
            $crate::ai::ai_list_threads,
            $crate::ai::ai_delete_thread,
            $crate::ai::ai_update_thread,
            $crate::ai::ai_list_thread_summaries,
            $crate::ai::ai_search_threads,
            $crate::ai::ai_add_message,
            $crate::ai::ai_get_messages,
            $crate::ai::ai_clear_messages,
            $crate::ai::ai_duplicate_thread,
            $crate::ai::ai_export_thread,
            $crate::ai::ai_import_thread,
            $crate::ai::ai_thread_count,
            // Cortex Session commands
            $crate::ai::cortex_create_session,
            $crate::ai::cortex_send_message,
            $crate::ai::cortex_approve_exec,
            $crate::ai::cortex_cancel,
            $crate::ai::cortex_get_status,
            $crate::ai::cortex_list_stored_sessions,
            $crate::ai::cortex_get_history,
            $crate::ai::cortex_destroy_session,
            $crate::ai::cortex_delete_session,
            $crate::ai::cortex_update_model,
            $crate::ai::cortex_update_cwd,
            $crate::ai::cortex_submit_system,
            // AI tools commands
            $crate::ai::tools::tools_list,
            $crate::ai::tools::tools_execute,
            $crate::ai::tools::tools_execute_batch,
            $crate::ai::tools::tools_get,
            // Agent commands
            $crate::ai::agents::commands::agent_spawn,
            $crate::ai::agents::commands::agent_run_task,
            $crate::ai::agents::commands::agent_cancel_task,
            $crate::ai::agents::commands::agent_list,
            $crate::ai::agents::commands::agent_get_status,
            $crate::ai::agents::commands::agent_get_task,
            $crate::ai::agents::commands::agent_list_tasks,
            $crate::ai::agents::commands::agent_remove,
            $crate::ai::agents::commands::agent_get_stats,
            $crate::ai::agents::commands::agent_cleanup,
            $crate::ai::agents::commands::agent_get_history,
            // Agent Store commands
            $crate::ai::agents::storage::agent_store_load,
            $crate::ai::agents::storage::agent_store_save,
            $crate::ai::agents::storage::agent_store_update_stats,
            $crate::ai::agents::storage::agent_store_add_history,
            $crate::ai::agents::prompt_generation::agent_generate_prompt,
            // AI predictions and misc commands
            $crate::ai::ai_predict,
            $crate::ai::submit_feedback,
            $crate::ai::fetch_url,
            // OpenRouter commands
            $crate::ai::set_openrouter_api_key,
            $crate::ai::get_openrouter_api_key,
            $crate::ai::openrouter_list_models,
            $crate::ai::openrouter_chat,
            $crate::ai::openrouter_stream_chat,
            // AI inline completions
            $crate::ai::completions::request_inline_completion,
            $crate::ai::completions::accept_completion,
            $crate::ai::completions::reject_completion,
            $crate::ai::completions::cancel_completion,
            // AI codebase indexing & context
            $crate::ai::indexer::index_workspace,
            $crate::ai::indexer::search_codebase,
            $crate::ai::context::get_ai_context,
            // Agent Factory commands
            $crate::factory::commands::factory_create_workflow,
            $crate::factory::commands::factory_update_workflow,
            $crate::factory::commands::factory_delete_workflow,
            $crate::factory::commands::factory_list_workflows,
            $crate::factory::commands::factory_get_workflow,
            $crate::factory::commands::factory_export_workflow,
            $crate::factory::commands::factory_import_workflow,
            $crate::factory::commands::factory_start_workflow,
            $crate::factory::commands::factory_stop_workflow,
            $crate::factory::commands::factory_pause_workflow,
            $crate::factory::commands::factory_resume_workflow,
            $crate::factory::commands::factory_get_execution_state,
            $crate::factory::commands::factory_list_agents,
            $crate::factory::commands::factory_create_agent,
            $crate::factory::commands::factory_update_agent,
            $crate::factory::commands::factory_delete_agent,
            $crate::factory::commands::factory_get_agent_state,
            $crate::factory::commands::factory_list_pending_approvals,
            $crate::factory::commands::factory_approve_action,
            $crate::factory::commands::factory_deny_action,
            $crate::factory::commands::factory_modify_action,
            $crate::factory::commands::factory_get_audit_log,
            $crate::factory::commands::factory_export_audit_log,
            $crate::factory::commands::factory_get_audit_entry,
        ])
    };
}
