#[macro_export]
macro_rules! extension_commands {
    (@commands $callback:ident [ $($acc:tt)* ]) => {
        $callback!([ $($acc)*
            // Extension commands - basic management
            $crate::extensions::commands::get_extensions,
            $crate::extensions::commands::get_enabled_extensions,
            $crate::extensions::commands::get_extension,
            $crate::extensions::commands::load_extensions,
            $crate::extensions::commands::enable_extension,
            $crate::extensions::commands::disable_extension,
            $crate::extensions::commands::uninstall_extension,
            $crate::extensions::commands::install_extension_from_path,
            $crate::extensions::commands::get_extensions_directory,
            $crate::extensions::commands::open_extensions_directory,
            $crate::extensions::commands::validate_extension_manifest,
            $crate::extensions::commands::update_extension,
            $crate::extensions::commands::get_activation_time_metrics,
            $crate::extensions::commands::update_all_extensions,
            // Extension commands - marketplace
            $crate::extensions::marketplace::search_marketplace,
            $crate::extensions::marketplace::get_featured_extensions,
            $crate::extensions::marketplace::install_from_marketplace,
            $crate::extensions::marketplace::check_extension_updates,
            $crate::extensions::marketplace::get_marketplace_categories,
            // Extension commands - contributions
            $crate::extensions::contributions::get_extension_themes,
            $crate::extensions::contributions::get_extension_commands,
            $crate::extensions::contributions::get_extension_languages,
            $crate::extensions::contributions::get_extension_panels,
            $crate::extensions::contributions::get_extension_settings,
            $crate::extensions::contributions::get_extension_keybindings,
            $crate::extensions::contributions::get_extension_snippets,
            $crate::extensions::contributions::execute_extension_command,
            // Extension commands - activation events
            $crate::extensions::activation::check_activation_event,
            $crate::extensions::activation::get_activation_status,
            $crate::extensions::activation::trigger_activation_event,
            // Extension commands - registry
            $crate::extensions::registry::registry_search,
            $crate::extensions::registry::registry_get_plugin,
            $crate::extensions::registry::registry_install,
            $crate::extensions::registry::registry_check_updates,
            $crate::extensions::registry::registry_check_updates_enabled,
            $crate::extensions::registry::set_auto_update_extensions,
            $crate::extensions::registry::registry_resolve_dependencies,
            // Extension commands - permissions
            $crate::extensions::permissions::plugin_check_permission,
            $crate::extensions::permissions::plugin_grant_permission,
            $crate::extensions::permissions::plugin_revoke_permission,
            $crate::extensions::permissions::plugin_respond_permission_request,
            $crate::extensions::permissions::plugin_request_shell_execution,
            $crate::extensions::permissions::plugin_get_grants,
            $crate::extensions::permissions::plugin_set_workspace_folders,
            // Extension commands - plugin API
            $crate::extensions::plugin_api::plugin_api_register_command,
            $crate::extensions::plugin_api::plugin_api_get_commands,
            $crate::extensions::plugin_api::plugin_api_show_message,
            // Extension commands - plugin API (commands)
            $crate::extensions::api::commands::plugin_register_command,
            $crate::extensions::api::commands::plugin_execute_command,
            $crate::extensions::api::commands::plugin_get_commands,
            // Extension commands - plugin API (window)
            $crate::extensions::api::window::plugin_show_message,
            $crate::extensions::api::window::plugin_show_quick_pick,
            $crate::extensions::api::window::plugin_respond_quick_pick,
            $crate::extensions::api::window::plugin_show_input_box,
            $crate::extensions::api::window::plugin_respond_input_box,
            $crate::extensions::api::window::plugin_create_output_channel,
            $crate::extensions::api::window::plugin_set_status_bar_message,
            $crate::extensions::api::window::plugin_show_progress,
            $crate::extensions::api::window::plugin_create_terminal,
            // Extension commands - plugin API (workspace)
            $crate::extensions::api::workspace::plugin_get_configuration,
            $crate::extensions::api::workspace::plugin_open_text_document,
            $crate::extensions::api::workspace::plugin_save_all,
            $crate::extensions::api::workspace::plugin_apply_edit,
            $crate::extensions::api::workspace::plugin_find_files,
            $crate::extensions::api::workspace::plugin_create_file_watcher,
            $crate::extensions::api::workspace::plugin_on_config_change,
            // Extension commands - plugin API (languages)
            $crate::extensions::api::languages::plugin_register_completion_provider,
            $crate::extensions::api::languages::plugin_register_hover_provider,
            $crate::extensions::api::languages::plugin_register_definition_provider,
            $crate::extensions::api::languages::plugin_register_diagnostics,
            $crate::extensions::api::languages::plugin_register_reference_provider,
            $crate::extensions::api::languages::plugin_unregister_reference_provider,
            $crate::extensions::api::languages::plugin_register_document_symbol_provider,
            $crate::extensions::api::languages::plugin_unregister_document_symbol_provider,
            $crate::extensions::api::languages::plugin_register_workspace_symbol_provider,
            $crate::extensions::api::languages::plugin_unregister_workspace_symbol_provider,
            $crate::extensions::api::languages::plugin_register_code_actions_provider,
            $crate::extensions::api::languages::plugin_unregister_code_actions_provider,
            $crate::extensions::api::languages::plugin_register_code_lens_provider,
            $crate::extensions::api::languages::plugin_unregister_code_lens_provider,
            $crate::extensions::api::languages::plugin_register_document_formatting_provider,
            $crate::extensions::api::languages::plugin_unregister_document_formatting_provider,
            $crate::extensions::api::languages::plugin_register_on_type_formatting_provider,
            $crate::extensions::api::languages::plugin_unregister_on_type_formatting_provider,
            $crate::extensions::api::languages::plugin_register_rename_provider,
            $crate::extensions::api::languages::plugin_unregister_rename_provider,
            $crate::extensions::api::languages::plugin_register_semantic_tokens_provider,
            $crate::extensions::api::languages::plugin_unregister_semantic_tokens_provider,
            $crate::extensions::api::languages::plugin_create_diagnostic_collection,
            // Extension commands - plugin API (debug)
            $crate::extensions::api::debug::plugin_register_debug_config_provider,
            $crate::extensions::api::debug::plugin_on_debug_session_start,
            $crate::extensions::api::debug::plugin_on_debug_session_end,
            // Extension commands - plugin API (scm)
            $crate::extensions::api::scm::plugin_register_source_control,
            $crate::extensions::api::scm::plugin_create_source_control,
            // WASM extension runtime commands
            $crate::extensions::wasm::load_wasm_extension,
            $crate::extensions::wasm::unload_wasm_extension,
            $crate::extensions::wasm::execute_wasm_command,
            $crate::extensions::wasm::get_wasm_runtime_states,
            // Node.js extension host commands
            $crate::extensions::node_host::extension_host_start,
            $crate::extensions::node_host::extension_host_stop,
            $crate::extensions::node_host::extension_host_install_vsix,
            $crate::extensions::node_host::extension_host_list_installed,
            $crate::extensions::node_host::extension_host_send_message,
        ])
    };
}
